-- Migration 0013: originally re-added active_customer_id / web_user_customer_links,
-- duplicating 0012_multi_customer.sql. On any database where 0012 ran to completion
-- (every CI run, since CI always starts from an empty database) its first statement
-- (ALTER TABLE web_users ADD COLUMN active_customer_id) fails with a duplicate-column
-- error, since 0012 already added that column, table, and FK. This is why CI's
-- "Run DB migrations" step has been failing since this migration was introduced.
--
-- 0012 already covers everything this migration attempted, so it is now a no-op.
-- Left in place (rather than deleted) to preserve migration history/ordering for any
-- environment that already recorded it as applied.
SELECT 1;
